name: 'AWS Secrets Manager Action'
author: 'Abhilash Kishore'
description: 'Use secrets from AWS Secrets Manager as environment variables in your GitHub Actions workflow'
inputs:
  secrets:
    description: 'List of secret names you want to fetch secret values for'
    required: true
  parse-json:
    description: 'If true and secret values are stringified JSON objects, they will be parsed and flattened. Its key value pairs will become individual secrets'
    required: false
    default: 'false'
  suppress-posix-warning:
    description: 'If false, names (keys) of secrets not matching POSIX validation, are notified in the log as warnings.'
    required: false
    default: 'true'
  add-to-steps-env:
    description: 'If true, the secret values will be automatically added to the env property of each following step.'
    required: false
    default: 'true'
  add-to-step-output:
    description: 'If true, the secret values will be automatically added to the step output and available for each following step.'
    required: false
    default: 'true'
  mask-secrets:
    description: 'If true, the secret values will be automatically masked within the log showing "***".'
    required: false
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
